return {
    unoccupied = Color3.fromRGB(20, 20, 20),
    blocked = Color3.fromRGB(25, 25, 25),

    occupied = {
        red = Color3.fromRGB(255, 55, 55),
        orange = Color3.fromRGB(255, 155, 55),
        yellow = Color3.fromRGB(255, 255, 55),
        green = Color3.fromRGB(55, 255, 122),
        lblue = Color3.fromRGB(55, 255, 222),
        dblue = Color3.fromRGB(55, 122, 255),
        purple = Color3.fromRGB(155, 55, 255),
        brown = Color3.fromRGB(155, 94, 33),
        grey = Color3.fromRGB(100, 100, 100)
    }
}