return {
    padding = 3,
    colours = {
        unoccupied = Color3.fromRGB(20, 20, 20),
        occupied = {
            red = Color3.fromRGB(255, 55, 55),
            orange = Color3.fromRGB(255, 155, 55),
            yellow = Color3.fromRGB(255, 255, 55),
            green = Color3.fromRGB(55, 255, 122),
            lblue = Color3.fromRGB(55, 255, 222),
            dblue = Color3.fromRGB(55, 122, 255),
            purple = Color3.fromRGB(155, 55, 255),
            brown = Color3.fromRGB(155, 94, 33),
            grey = Color3.fromRGB(100, 100, 100)
        },
        valid = {
            transparency = 0.9,
            colour = Color3.new(1, 1, 1)
        },
        invalid = {
            transparency = 0.9,
            colour = Color3.new(1, 0.2, 0.2)
        }
    }
}